"""Generate pruned Popper task directories."""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional, Set

from .models import Guidance, PredicateSpec, TaskData
from .prolog import literal_to_text


def write_pruned_task(
    task: TaskData,
    guidance: Guidance,
    output_dir: str | Path,
    bk_slice_examples: bool = False,
    bk_slice_depth: int = 1,
    max_facts_per_predicate: Optional[int] = None,
) -> Path:
    """Create a Popper task directory with a pruned bias.pl.

    `bk.pl` and `exs.pl` are copied unchanged.  Only the search bias is pruned,
    which keeps the clean fact base reusable across ILP, LLM-only, and PARA
    experiments.
    """

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    src = Path(task.task_dir)

    # 背景事实也需要随谓词选择一起剪枝。
    # 早期版本只剪 bias.pl，但复杂元模型下 bk.pl 很大，Popper grounding 仍然很慢。
    # 这里保留 selected body predicates 对应事实；可选地进一步只保留训练例常量邻域内的事实。
    write_pruned_bk(
        task,
        guidance,
        out / "bk.pl",
        slice_examples=bk_slice_examples,
        slice_depth=bk_slice_depth,
        max_facts_per_predicate=max_facts_per_predicate,
    )
    (out / "exs.pl").write_text((src / "exs.pl").read_text(encoding="utf-8"), encoding="utf-8")

    # 搜索空间剪枝只体现在 bias.pl：
    # body_pred 数量越少，Popper 枚举的候选规则组合越少。
    (out / "bias.pl").write_text(build_bias_text(task, guidance), encoding="utf-8")
    return out


def write_pruned_bk(
    task: TaskData,
    guidance: Guidance,
    output_file: Path,
    slice_examples: bool = False,
    slice_depth: int = 1,
    max_facts_per_predicate: Optional[int] = None,
) -> None:
    """Write a background file containing only selected predicate facts."""

    selected = set(guidance.selected_predicates)
    selected_specs = [spec for name in guidance.selected_predicates if (spec := find_predicate_by_name(task, name))]
    allowed_terms = example_seed_terms(task) if slice_examples else None

    lines: List[str] = ["% Auto-generated by PARA", "% Pruned background knowledge", ""]
    if slice_examples:
        lines.extend(
            [
                f"% BK slice around example constants enabled: depth={slice_depth}",
                "% This keeps Popper grounding closer to the train/test boundary.",
                "",
            ]
        )

    # 先写 fail 占位，避免某个被选中谓词在当前切片中没有事实时被 Prolog 视为未定义。
    for spec in selected_specs:
        args = ",".join("_" for _ in range(spec.arity))
        lines.append(f"{spec.name}({args}) :- fail.")
    lines.append("")

    kept = selected_facts(
        task,
        selected,
        allowed_terms=allowed_terms,
        slice_depth=slice_depth,
        max_facts_per_predicate=max_facts_per_predicate,
    )
    for fact in kept:
        lines.append(literal_to_text(fact) + ".")

    output_file.write_text("\n".join(lines) + "\n", encoding="utf-8")


def selected_facts(
    task: TaskData,
    selected_predicates: Set[str],
    allowed_terms: Optional[Set[str]] = None,
    slice_depth: int = 1,
    max_facts_per_predicate: Optional[int] = None,
) -> List:
    """Return selected BK facts, optionally limited to an example-neighborhood slice.

    大型项目上真正的瓶颈不是 bias.pl 中有多少个谓词名，而是这些谓词对应的
    ground facts 太多。该函数先按 LLM 选中的谓词过滤，再从正负例中出现的常量
    出发做若干轮邻域扩展，只保留和训练例可连接的事实。
    """

    selected = [fact for fact in task.facts if fact.predicate in selected_predicates]
    if allowed_terms is None:
        return limit_facts_per_predicate(selected, max_facts_per_predicate)

    frontier = set(allowed_terms)
    kept = []
    seen = set()
    depth = max(0, slice_depth)
    for _ in range(depth + 1):
        next_frontier = set(frontier)
        for fact in selected:
            key = (fact.predicate, fact.args)
            if key in seen:
                continue
            if any(arg in frontier for arg in fact.args):
                kept.append(fact)
                seen.add(key)
                next_frontier.update(fact.args)
        if next_frontier == frontier:
            break
        frontier = next_frontier
    return limit_facts_per_predicate(kept, max_facts_per_predicate)


def example_seed_terms(task: TaskData) -> Set[str]:
    """Collect constants from positive and negative examples as BK slice seeds."""

    terms: Set[str] = set()
    for example in task.examples:
        terms.update(example.literal.args)
    return terms


def limit_facts_per_predicate(facts: List, max_facts_per_predicate: Optional[int]) -> List:
    """Apply a deterministic cap per predicate after semantic slicing."""

    if not max_facts_per_predicate or max_facts_per_predicate <= 0:
        return facts
    counts = {}
    output = []
    for fact in facts:
        count = counts.get(fact.predicate, 0)
        if count >= max_facts_per_predicate:
            continue
        output.append(fact)
        counts[fact.predicate] = count + 1
    return output


def build_bias_text(task: TaskData, guidance: Guidance) -> str:
    lines: List[str] = []
    target = task.target
    lines.append("% Auto-generated by PARA")
    lines.append(f"head_pred({target.name},{target.arity}).")

    selected_specs = []
    for name in guidance.selected_predicates:
        spec = find_predicate_by_name(task, name)
        if spec is not None:
            selected_specs.append(spec)
            lines.append(f"body_pred({spec.name},{spec.arity}).")
    lines.append("")

    # 类型声明保留 Popper 的类型化搜索能力，避免生成 package/class 混用的无效规则。
    if target.types:
        lines.append(f"type({target.name},{_type_tuple(target.types)}).")
    for spec in selected_specs:
        if spec.types:
            lines.append(f"type({spec.name},{_type_tuple(spec.types)}).")
    lines.append("")

    # max_* 是 Popper 假设空间大小的直接控制旋钮。
    # LLM/启发式反馈可以逐轮调节这些值。
    lines.append(f"max_vars({guidance.max_vars}).")
    lines.append(f"max_body({guidance.max_body}).")
    lines.append(f"max_clauses({guidance.max_clauses}).")
    lines.append("")

    # 把完整排序写入注释，方便复现实验时解释“为什么保留这些谓词”。
    lines.append("% Ranked predicates:")
    for idx, name in enumerate(guidance.ranked_predicates, start=1):
        lines.append(f"% {idx}. {name}")
    lines.append("")
    return "\n".join(lines)


def find_predicate_by_name(task: TaskData, name: str) -> PredicateSpec | None:
    # Guidance 中只保存谓词名，写 bias 时需要恢复 arity 和 type 信息。
    for spec in task.predicates.values():
        if spec.name == name:
            return spec
    return None


def _type_tuple(types: tuple[str, ...]) -> str:
    """Write Popper-compatible tuple syntax.

    Popper expects unary tuples with a trailing comma, e.g. `(class,)`.
    Without the comma, clingo's helper script can fail while reading type
    declarations for arity-1 predicates.
    """

    if len(types) == 1:
        return f"({types[0]},)"
    return f"({','.join(types)})"
